/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AccountTransformer from '#transformers/account_transformer'
import type PlatformTransformer from '#transformers/platform_transformer'
import type ProfileTransformer from '#transformers/profile_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Account = InferData<AccountTransformer>
  export namespace Account {
    export type Variants = InferVariants<AccountTransformer>
  }
  export type Platform = InferData<PlatformTransformer>
  export namespace Platform {
    export type Variants = InferVariants<PlatformTransformer>
  }
  export type Profile = InferData<ProfileTransformer>
  export namespace Profile {
    export type Variants = InferVariants<ProfileTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
